### ISSUE TITLE
SQL_Express_Backups.sql typo in variable name

### ISSUE THREAD

**Issue by db4rne** [microsoft/mssql-support#2]
I just tried using your SQL_Express_Backups.sql file to do Backups as described [https://docs.microsoft.com/en-us/troubleshoot/sql/admin/schedule-automate-backup-database](here). Unfortunately, creating the SP doesn't work because in line 25, there is a typo and `DatabaseName` should actually be `databaseName`.

I would have created a PR, but the CLA process seems a bit much for a minor thing like this.

**Comment by suresh-kandoth** [comment]
@db4rne : Thanks for reporting this. Fixed this in the latest update.
