### ISSUE TITLE
SQL_Express_Backups.sql - declaration of @backupLocation and @BackupFile do not match

### ISSUE THREAD

**Issue by andreasjordan** [microsoft/mssql-support#3]
https://github.com/microsoft/mssql-support/blob/546172280c95136d9f9eb7b2a7af5099cbfba4bc/sample-scripts/backup_restore/SQL_Express_Backups.sql#L22

https://github.com/microsoft/mssql-support/blob/546172280c95136d9f9eb7b2a7af5099cbfba4bc/sample-scripts/backup_restore/SQL_Express_Backups.sql#L56

https://github.com/microsoft/mssql-support/blob/546172280c95136d9f9eb7b2a7af5099cbfba4bc/sample-scripts/backup_restore/SQL_Express_Backups.sql#L70-L75

With long paths, @BackupFile is truncated after 100 characters.

**Comment by suresh-kandoth** [comment]
@andreasjordan - thanks for reporting this. Fixed those issues in the latest version.
