### ISSUE TITLE
typo in mssql error string?

### ISSUE THREAD

**Issue by pine3ree** [microsoft/mssql-support#6]
I receive this error message using the wrong clause "FETCH NEXT 0 ROWS ONLY". I thought it was a wrapper library message, but I get it from mssql-cli as well

`The number of rows provided for a FETCH clause must be greater then zero.`

Shouldn't it be:
`The number of rows provided for a FETCH clause must be greater thAn zero.`

?

linux mssql-server 15.0.4073-23.4

**Comment by PiJoCoder** [comment]
@pine3ree , thank you for your sumbission. The spelling mistake you pointed out is inside the SQL Server engine, not in any of the scripts in this repository. We will let the teams know about it. Thank you
You can find this by running against any SQL Server:

```
select * from sys.messages
where message_id = 10744
and language_id = 1033
```
